apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: messaging-app
data:
  DB_HOST: app-service
  DB_PORT: "5432"
  DEBUG: "True"
  DJANGO_ALLOWED_HOSTS: localhost
  DATABASE_ENGINE: postgresql_psycopg2
