apiVersion: apps/v1
kind: Deployment
metadata:
  name: messaging-app-deployment
  namespace: messaging-app1
  labels: 
    app: django
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: django
  template:
    metadata:
      labels: 
        app: django
    spec:
      containers:
        - name: django
          image: django-app:latest
          imagePullPolicy: Never
          command: ["/app/entrypoint"]
          ports:
            - containerPort: 8081
          envFrom:
            - configMapRef:
                name: app-config 
            - secretRef:
                name: db-secret-credentials

---

apiVersion: v1
kind: Service
metadata:
  name: messaging-app-service
  namespace: messaging-app1
spec:
  selector:
    app: django
  ports:
    - protocol: TCP
      port: 8081          # Port exposed inside the cluster
      targetPort: 8081   # Matches containerPort
  type: NodePort          # Allows access from outside the cluster (Minikube)
