#!/bin/bash

set -e
set -x

if ! command -v minikube &> /dev/null
then 
    echo "Minikube is not installed. Install it using: "
    echo "'https://minikube.sigs.k8s.io/docs/start/' or 'choco install minikube -y' if you have chocolty installed"
    exit 1
fi

echo "Starting minikube cluster..."
minikube start --driver=docker

echo "Verifying cluster status..."
kubectl cluster-info || {
    echo "cluster verification faild";
    exit 1
}

echo "Retrieving available pods..."
kubectl get pods -A

echo "kubernetes cluster is running successfully"

