apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysqldb-pvc 
  namespace: messaging-app1
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Mi
  volumeName: mysqldb-pv
