apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc 
  namespace: nessaging-app
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resouces:
    requests:
      storage: 50M
    volumeName: postgres-pv
