apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysqldb
  namespace: messaging-app1
spec:
  replicas: 1
  selector:
    matchLabels: 
      app: mysqldb  
  template:
    metadata:
      labels:
        app: mysqldb
    spec:
      containers:
        - name: mysqldb
          image: mysql:8.0.36
          ports:
            - containerPort: 5432
          envFrom:
            - secretRef: 
                name: db-secret-credentials
          volumeMounts:
            - mountPath: var/lib/mysql
              name: db-data
      volumes:
        - name: db-data
          persistentVolumeClaim:
            claimName: mysqldb-pvc
