FROM jenkins/jenkins:lts

USER root

# Install Git and Python
RUN apt-get update && \
    apt-get install -y git python3 python3-pip python3-venv && \
    rm -rf /var/lib/apt/lists/*

# Switch back to Jenkins user
USER jenkins