#!/bin/bash
APP_PORT=${PORT:-8081}
echo "Waiting for MySQL..."

./wait-for-it.sh db:3306 --timeout=60 --strict -- echo "MySQL is up"


cd /app

# run migration
/bin/bash /app/migrate

/venv/bin/gunicorn --worker-tmp-dir /dev/shm messaging_app.wsgi:application --bind "0.0.0.0:${APP_PORT}"
